---
- name: update cache
  apt: update_cache=yes
  
- name: install vim
  apt: pkg=vim-nox state=installed

- name: install pip
  apt: pkg=python-pip state=latest

- name: install boto
  pip: name=boto state=latest

- name: install AWS CLI
  pip: name=awscli state=latest

#- name: Set up iptables rules
#  copy: src=iptables-save dest=/etc/iptables.cfg
#  notify: restart iptables
