---
- name: update cache
  apt: update_cache=yes
  
- name: install vim
  apt: pkg=vim-nox state=installed

#- name: Set up iptables rules
#  copy: src=iptables-save dest=/etc/iptables.cfg
#  notify: restart iptables
