---
- name: Example of provisioning servers
  hosts: localhost
  connection: local
  tasks:
    - name: Launch instances
      local_action:
        module: ec2
        region: us-east-1
        keypair: tokidoki
        group: tokidoki-admin
        instance_type: m3.xlarge
        image: ami-a73264ce
        count: 2
        wait: yes
      register: ec2

    - name: Add EBS volume
      local_action: ec2_vol volume_size=60 instance={{ item.id }} region=us-east-1 
      with_items: ec2.instances

    - name: Add instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=tokishop
      with_items: ec2.instances

    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: tokishop%04d
          Class: magento



#    - name: Add EBS volume
#      local_action:
#        module: ec2_vol
#        instance: "{{ item.id }}"
#        volume_size: 60
#        with_items: ec2.instances
#      register: ec2_vol

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances



- name: Configure provisioned servers
  hosts: tokishop
  user: ubuntu
  sudo: True
  roles:
    - common
