---
- name: Install Magento, Nginx, and PHP-FPM on web servers
  hosts: web
  user: vagrant
  sudo: yes

  roles:
    - common
    - nginx
    - php-fpm
    - magento

- name: Install MySQL on DB servers
  hosts: db
  user: root

  roles:
    - mysql
