---
- name: Install required packages for apt_repository
  apt: name={{ item }} state=present
  with_items:
  - python-apt
  - python-pycurl

- name: Add MySQL 5.6 PPA
  apt_repository: repo='ppa:ondrej/mysql-5.6' state=present

- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mysql-server-5.6
   - python-mysqldb

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Create Magento database
  mysql_db: name={{ mag_db_name }} state=present

- name: Create Magento database user
  mysql_user: name={{ mag_db_user }} password={{ mag_db_password }} priv={{ mag_db_name }}.*:ALL host={{ mag_app_ip }} state=present
